// List of All Spells
export const LOAD_ALL_SPELLS = 'LOAD_ALL_SPELLS'
export const SET_ALL_SPELLS_FILTER = 'SET_ALL_SPELLS_FILTER'
export const SET_FILTERED_ALL_SPELLS = 'SET_FILTERED_ALL_SPELLS'

// List of Prepared Spells
export const LOAD_PREPARED_SPELLS = 'LOAD_PREPARED_SPELLS'
export const SET_PREPARED_SPELLS_FILTER = 'SET_PREPARED_SPELLS_FILTER'
export const SET_FILTERED_PREPARED_SPELLS = 'SET_FILTERED_PREPARED_SPELLS'

// List of Known Spells
export const LOAD_KNOWN_SPELLS = 'LOAD_KNOWN_SPELLS'
export const SET_KNOWN_SPELLS_FILTER = 'SET_KNOWN_SPELLS_FILTER'
export const SET_FILTERED_KNOWN_SPELLS = 'SET_FILTERED_KNOWN_SPELLS'

// Auth State
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

// Character management
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS'
export const CREATE_CHARACTER = 'CREATE_CHARACTER'
export const UPDATE_ALL_CHARACTERS = 'UPDATE_ALL_CHARACTERS'
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER'
export const DELETE_CHARACTER = 'DELETE_CHARACTER'
export const CLEAR_CHARACTERS = 'CLEAR_CHARACTERS'

// Spell Management
export const LEARN_SPELL = 'LEARN_SPELL'
export const FORGET_SPELL = 'LEARN_SPELL'
export const PREPARE_SPELL = 'PREPARE_SPELL'
export const UNPREPARE_SPELL = 'UNPREPARE_SPELL'
export const CLEAR_SPELLS = 'CLEAR_SPELLS' // TODO: on logout
